<a href="https://colab.research.google.com/github/sak2004/Neural_Network_From_Scratch/blob/main/Neural_Network_UsingNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np

# Creation two layers of 3 neurons and inputing 4 variables

In [9]:


inputs = [[1, 2, 3, 2.5],   # 4 inputs to neuron
          [2., 5., -1., 2],
          [-1.5, 2.7, 3.3, -0.8]]

weights = [[0.2, 0.8, -0.5, 1],
           [0.5, -0.91, 0.26, -0.5],    # weights for each input to 3 neuron
           [-0.26, -0.27, 0.17, 0.87]]

biases = [2, 3, 0.5] # biases for each neuron

weights2 = [[0.1, -0.14, 0.5],
            [-0.5, 0.12, -0.33],
            [-0.44, 0.73, -0.13]]

biases2 = [-1, 2, -0.5]

# Convert lists to numpy arrays
inputs_array = np.array(inputs)
weights_array = np.array(weights)
biases_array = np.array(biases)
weights2_array = np.array(weights2)
biases2_array = np.array(biases2)

# Calculate the output of the first layer
layer1_outputs = np.dot(inputs_array, weights_array.T) + biases_array

# Calculate the output of the second layer
layer2_outputs = np.dot(layer1_outputs, weights2_array.T) + biases2_array

print(layer2_outputs) # here input value passed though two layers using simple matrix multiplication between input and transpose of weights and addition of biases

[[ 0.50310004 -1.04184985 -2.03874993]
 [ 0.24339998 -2.73320007 -5.76329994]
 [-0.99314     1.41254002 -0.35655001]]


#Creating Dense Function Class


In [10]:

class Layer_Dense:
  def __init__(self,n_inputs,n_neurons):
    self.weights = 0.10 * np.random.randn(n_inputs,n_neurons)
    self.biases = np.zeros((1,n_neurons))
  def forward_pass(self,inputs):
    self.output = np.dot(inputs,self.weights) + self.biases

dense1 = Layer_Dense(2,3)
dense1.forward_pass(X)
print(dense1.output[:5])



[[ 0.          0.          0.        ]
 [-0.00104752  0.00113954 -0.00047984]
 [-0.00274148  0.00317292 -0.00086922]
 [-0.00421884  0.00526663 -0.00055913]
 [-0.00577077  0.00714014 -0.0008943 ]]


#Implementing Activation Layers


Implementing ReLu Class as Activation Layer

In [11]:
class Activation_Relu :
  def forward_pass(self,inputs):
    self.output = np.maximum(0,inputs)


Implementing Softmax Activation Function for predicted Outputs

In [12]:
class Activation_Softmax:
  def forward_pass(self,inputs):

    exp_value = np.exp(inputs - np.max(inputs,axis=1,keepdims=True))
    probabilities = exp_value / np.sum(exp_value,axis=1,keepdims=True)
    self.output = probabilities

# Implementing Neural Network on Spiral Dataset

In [13]:
pip install nnfs

In [14]:
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
import nnfs #using nnfs to generate a spiral data set
from nnfs.datasets import spiral_data
nnfs.init()
X,y =spiral_data(samples=100,classes= 3)

In [15]:

dense1=Layer_Dense(2,3)
activation1=Activation_Relu()
dense2=Layer_Dense(3,3)
activation2=Activation_Softmax()
dense1.forward_pass(X)
activation1.forward_pass(dense1.output)
dense2.forward_pass(activation1.output)
activation2.forward_pass(dense2.output)
print(activation2.output[:5])  # here output for radom weights selection gave really poor out so we need to find a way optimaize the weights selection ;(


[[0.33333334 0.33333334 0.33333334]
 [0.33331734 0.3333183  0.33336434]
 [0.3332888  0.33329153 0.33341965]
 [0.33325943 0.33326396 0.33347666]
 [0.33323312 0.33323926 0.33352762]]


# Implementing Cross Entropy Catregorical loss class

Implementing common loss function

In [16]:
class Loss:
  def calculate(self,output,y):
    sample_losses = self.forward(output,y)
    data_loss = np.mean(sample_losses)
    return data_loss

In [17]:
class Loss_CategoricalCrossentropy(Loss):
  def forward(self,y_pred,y_true):
    samples = len(y_pred)
    y_prep_clipped = np.clip(y_pred,1e-7,1-1e-7)

    if len(y_true.shape) == 1:
      correct_confidences = y_prep_clipped[range(samples),y_true]
    elif len(y_true.shape)==2:
      correct_confidences= np.sum(y_prep_clipped*y_true,axis=1)
    negative_log_likelihood = -np.log(correct_confidences)
    return negative_log_likelihood

In [19]:
X,y =spiral_data(samples=100,classes= 3)

dense1=Layer_Dense(2,3)
activation1=Activation_Relu()
dense2=Layer_Dense(3,3)
activation2=Activation_Softmax()
loss_function = Loss_CategoricalCrossentropy()
dense1.forward_pass(X)
activation1.forward_pass(dense1.output)
dense2.forward_pass(activation1.output)
activation2.forward_pass(dense2.output)
print(activation2.output[:5])

loss = loss_function.calculate(activation2.output,y)
print("Loss:",loss)



[[0.33333334 0.33333334 0.33333334]
 [0.33333334 0.33333334 0.33333334]
 [0.33333334 0.33333334 0.33333334]
 [0.33333334 0.33333334 0.33333334]
 [0.33333334 0.33333334 0.33333334]]
Loss: 1.0999713
