<a href="https://colab.research.google.com/github/sak2004/Neural_Network_From_Scratch/blob/main/Neural_Network_UsingNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

# Creation two layers of 3 neurons and inputing 4 variables

In [3]:


inputs = [[1, 2, 3, 2.5],   # 4 inputs to neuron
          [2., 5., -1., 2],
          [-1.5, 2.7, 3.3, -0.8]]

weights = [[0.2, 0.8, -0.5, 1],
           [0.5, -0.91, 0.26, -0.5],    # weights for each input to 3 neuron
           [-0.26, -0.27, 0.17, 0.87]]

biases = [2, 3, 0.5] # biases for each neuron

weights2 = [[0.1, -0.14, 0.5],
            [-0.5, 0.12, -0.33],
            [-0.44, 0.73, -0.13]]

biases2 = [-1, 2, -0.5]

# Convert lists to numpy arrays
inputs_array = np.array(inputs)
weights_array = np.array(weights)
biases_array = np.array(biases)
weights2_array = np.array(weights2)
biases2_array = np.array(biases2)

# Calculate the output of the first layer
layer1_outputs = np.dot(inputs_array, weights_array.T) + biases_array

# Calculate the output of the second layer
layer2_outputs = np.dot(layer1_outputs, weights2_array.T) + biases2_array

print(layer2_outputs) # here input value passed though two layers using simple matrix multiplication between input and transpose of weights and addition of biases

[[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]


In [5]:
pip install nnfs

In [ ]:
import nnfs #using nnfs to generate a spiral data set
from nnfs.datasets import spiral_data
nnfs.init()
X,y =spiral_data(samples=100,classes= 3)

#Creating Dense Function Class


In [6]:

class Layer_Dense:
  def __init__(self,n_inputs,n_neurons):
    self.weights = 0.10 * np.random.randn(n_inputs,n_neurons)
    self.biases = np.zeros((1,n_neurons))
  def forward_pass(self,inputs):
    self.output = np.dot(inputs,self.weights) + self.biases

dense1 = Layer_Dense(2,3)
dense1.forward_pass(X)
print(dense1.output[:5])



[[ 0.          0.          0.        ]
 [-0.00104752  0.00113954 -0.00047984]
 [-0.00274148  0.00317292 -0.00086922]
 [-0.00421884  0.00526663 -0.00055913]
 [-0.00577077  0.00714014 -0.0008943 ]]


#Implementing Activation Layers


Implementing ReLu Class as Activation Layer

In [7]:
class Activation_Relu :
  def forward_pass(self,inputs):
    self.output = np.maximum(0,inputs)


Implementing Softmax Activation Function for predicted Outputs

In [10]:
class Activation_Softmax:
  def forward(self,inputs):

    exp_value = np.exp(inputs - np.max(inputs,axis=1,keepdims=True))
    probabilities = exp_value / np.sum(exp_value,axis=1,keepdims=True)
    self.output = probabilities